# Site settings
title: Xeph
description: 'Purple Teaming - Exploit Dev'
url: 'https://xepher.us'
baseurl: ''
google_analytics: 'UA-150390413-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Xeph'
  email: xeph@xepher.us
  twitter_username: Xeno_net
#  facebook_username: joshgerdes
#  github_username:  joshgerdes
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
